name: ğŸ“ˆ Generate Code Coverage Report
on:
  push:
    branches:
      - master

jobs:
  generate-report:
    name: Create Report
    runs-on: ubuntu-22.04
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.code-ref }}

      - name: âš™ï¸ Install Tarpaulin
        run: cargo install cargo-tarpaulin@0.33.0

      - name: ğŸ“ˆ Generate Report
        run: |
          cargo tarpaulin --out html --output-dir reports -- --test-threads=1
          mv ./reports/tarpaulin-report.html ./reports/index.html

      - name: âš™ï¸ Setup Pages
        uses: actions/configure-pages@v5

      - name: ğŸ“¤ Upload Report
        id: upload-report
        uses: actions/upload-pages-artifact@v4
        with:
          path: reports

  publish-pages:
    name: Publish Pages
    runs-on: ubuntu-22.04
    needs: generate-report
    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: ğŸš€ Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
