name: ğŸ“ˆ Generate Code Coverage Report
on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  generate-report:
    name: Create Report
    runs-on: ubuntu-22.04
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.code-ref }}

      - name: âš™ï¸ Install llvm-cov
        run: cargo install cargo-llvm-cov@0.6.21

      - name: ğŸ“ˆ Generate Report
        run: cargo llvm-cov --html -- --test-threads=1

      - name: âš™ï¸ Setup Pages
        uses: actions/configure-pages@v5

      - name: ğŸ“¤ Upload Report
        id: upload-report
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./target/llvm-cov/html

  publish-pages:
    name: Publish Pages
    runs-on: ubuntu-22.04
    needs: generate-report
    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: ğŸš€ Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
